name: Terraform Deploy

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 🔑 AWS Credentials Step (Yeh naya add kiya hai)
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # ⚠️ Agar aapka region alag hai (jaise ap-south-1), toh yahan change kar lein

      - name: Init
        run: terraform init

      - name: Plan
        run: terraform plan

      - name: Apply
        run: terraform apply -auto-approve
